config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  namespace :admin do
    resources :users
    resources :products do
      resources :uploads
    end
  end
  resources :stores

  resources :products do
    resources :comments
  end

  resources :favorite_products

  devise_for :users
  get 'pages/home'

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end

  def add_item(cart_item)
    @items << cart_item
  end

  def subtotal
    sum = 0
    @items.each do |item|
      sum += item.total
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :product_id, :quantity

  def initialize(product_id, quantity)
    @product_id = product_id
    @quantity = quantity
  end

  def product
    Product.find(product_id)
  end

  def total
    product.price * quantity.to_i
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
  belongs_to :state
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :uploads, :dependent => :destroy

  validates :name, :price, :quantity, presence: true
  validates :description, presence: true, length: { maximum: 300 }

  def in_cart?(current_user_id)
    $redis.hexists "cart#{current_user_id}", id
  end

  def cart_quantity
    $redis.hget "cart#{current_user_id}", id
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :user
  has_many :cities
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :city
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base

  belongs_to :product

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products
  has_many :comments
  belongs_to :city
  has_one :store
  has_many :favorites
  has_many :favorite_products, through: :favorites,
            source: :favorited, source_type: 'Product'

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def cart_count
    $redis.hlen "cart#{id}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
     info = $redis.hgetall current_user_cart
     @cart = Cart.new
     info.each do |product_id, quantity|
       @cart.add_item(CartItem.new(product_id, quantity))
     end

     @cart
  end

  def add
    product_id = params[:product_id].to_i
    quantity = params[:quantity].to_i
    $redis.hset current_user_cart, product_id, quantity

    redirect_to product_path(product_id), notice: 'Product has been added to your cart.'
  end

  def remove
    product_id = params[:product_id].to_i
    $redis.hdel current_user_cart, product_id

    redirect_to :back, notice: 'Product has been removed from your cart.'
  end


  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:create, :destroy]
  before_action :authenticate_user!,   only: [:create, :destroy]

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user_id = current_user.id
    redirect_to product_path(@product)
    @comment = @product.save

  end

  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_path(@product)
  end

  private

    def set_comment
      @product = Product.find(params[:product_id])
    end

    # def correct_user
    #   @product = current_user.products.find(params[:id])
    #   redirect_to products_path if @product.nil?
    # end

    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticated

  def home
    @selection = Product.order("created_at DESC").limit(8)
  end

  # def authenticated
  #   redirect_to :products if signed_in?
  # end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stores = Store.all
    respond_with(@stores)
  end

  def show
    respond_with(@store)
  end

  def new
    @store = Store.new
    respond_with(@store)
  end

  def edit
  end

  def create
    @store = Store.new(store_params)
    @store.save
    respond_with(@store)
  end

  def update
    @store.update(store_params)
    respond_with(@store)
  end

  def destroy
    @store.destroy
    respond_with(@store)
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name, :city_id, :facebook, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_herlper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def quantity_options(stock)
    array = (1..stock).map do |x|
      [x, x]
    end

    options_for_select(array)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<nav class="progress">
  <ol>
    <li class="active"><a href="/cart">Your basket</a></li>
    <li class="active"><a href="/cart">Your basket</a></li>
    <li class="active"><a href="/cart">Your basket</a></li>
    <li class="active"><a href="/cart">Your basket</a></li>
  </ol>
  <span>25% complete</span>
</nav>

<div class="row shadow-wrapper">
  <div class="col-sm-12 col-md-10 col-md-offset-1" id="mycart">
    <table class="table">
      <thead>
        <tr>
          <th class="text-center">Product</th>
          <th class="text-center">Name</th>
          <th class="text-center">Quantity</th>
          <th class="text-center">Price</th>
          <th class="text-center">Total</th>
          <th class="text-center">Remove</th>
        </tr>
      </thead>
      <tbody>
      <% @cart.items.each do |item|%>
        <tr>
          <td class="col-sm-3 col-md-3 cart-product ">
            <div class="media text-center">
              <%= link_to image_tag(item.product.uploads.first.image.url(:thumb)), product_path(item.product) %>
              </div>
            </td>
            <td class="col-sm-2 col-md-2 text-center">
              <h4 class="media-heading"><%= link_to item.product.name, product_path(item.product) %></a></h4>
            </td>
            <td class="col-sm-2 col-md-2 text-center"><%= item.quantity %></td>
            </td>
            <td class="col-sm-2 col-md-2 text-center">$<%= item.product.price %></td>
            <td class="col-sm-2 col-md-2 text-center"><strong><%= item.total %></strong></td>
            <td class="col-sm-1 col-md-1 text-center">
            <%=link_to remove_from_cart_path(item.product), method: :put do%>
            <span class="glyphicon glyphicon-trash"></span>
            <%end%>
            </td>
        </tr>
        <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="col-sm-1 col-md-1 text-center"><h5>Subtotal</h5> </td>
          <td class="col-sm-2 col-md-2 text-center"><h5><strong><%= @cart.subtotal %></strong></h5></td>
          <td class="col-sm-3 col-md-3 text-center"></td>
        </tr>
        <tr>
          <td>   </td>
          <td>   </td>
          <td>   </td>
          <td><h5>Estimated shipping</h5></td>
          <td class="text-center"><h5><strong></strong></h5></td>
        </tr>
        <tr>
          <td>   </td>
          <td>   </td>
          <td>   </td>
          <td class="text-center"><h3>Total</h3></td>
          <td class="text-center"><h3><strong></strong></h3></td>
        </tr>


      </tbody>
    </table>

      <div class="pull-right">
        <%= link_to root_path, class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-shopping-cart">Continue shopping</i>
        <% end %>

        <button type="button" class="btn btn-success">
          Checkout <span class="glyphicon glyphicon-play"></span>
        </button></td>
      </div>

  </div>
</div>

app/views/comments/_comment.html.erb
<div class="media">
  <a class="media-left" href="#">
    <%= image_tag Gravatar.new(comment.user.email).image_url, :class => "image-circle" %>
  </a>
  <div class="media-body">
    <h4 class="media-heading"><%= comment.user.name %></h4>
    <span><%= l(comment.created_at, format: '%d %b %y') %></span>
    <p><%= comment.body %></p>
  </div>
</div>

<% if comment.user == current_user %>
<p>
  <%= link_to 'Delete Comment', [comment.product, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@product, @product.comments.build]) do |f| %>

  <div class="form-group">
    <%= f.text_area :body, :class => "form-control", :rows => "3" %>
  </div>
  <div class="form-actions  clearfix">
    <%= f.submit :class => "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.text_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.city %></td>
        <td><%= store.facebook %></td>
        <td><%= store.twitter %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @store.city %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @store.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @store.twitter %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>