config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  namespace :admin do
    resources :users
    resources :products do
      resources :uploads
    end
  end
  resources :stores

  resources :products do
    resources :comments
  end

  resources :favorite_products

  devise_for :users
  get 'pages/home'

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end

  def add_item(cart_item)
    @items << cart_item
  end

  def subtotal
    sum = 0
    @items.each do |item|
      sum += item.total
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :product_id, :quantity

  def initialize(product_id, quantity)
    @product_id = product_id
    @quantity = quantity
  end

  def product
    Product.find(product_id)
  end

  def total
    product.price * quantity.to_i
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
  belongs_to :state
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :uploads, :dependent => :destroy

  validates :name, :price, :quantity, presence: true
  validates :description, presence: true, length: { maximum: 300 }

  def in_cart?(current_user_id)
    $redis.hexists "cart#{current_user_id}", id
  end

  def cart_quantity
    $redis.hget "cart#{current_user_id}", id
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :user
  has_many :cities
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :city
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base

  belongs_to :product

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products
  has_many :comments
  belongs_to :city
  has_one :store
  has_many :favorites
  has_many :favorite_products, through: :favorites,
            source: :favorited, source_type: 'Product'

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def cart_count
    $redis.hlen "cart#{id}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/uploads_controller.rb
class Admin::UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @product = Product.find(params[:product_id])
    @upload = Upload.new

  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)
    @upload.product_id = params[:product_id]
    @upload.save
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    if @upload.update(upload_params)
      redirect_to @upload, notice: 'Upload was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    redirect_to [:admin, @upload.product]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params[:upload].permit(:image, :product_id)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
     info = $redis.hgetall current_user_cart
     @cart = Cart.new
     info.each do |product_id, quantity|
       @cart.add_item(CartItem.new(product_id, quantity))
     end

     @cart
  end

  def add
    product_id = params[:product_id].to_i
    quantity = params[:quantity].to_i
    $redis.hset current_user_cart, product_id, quantity

    redirect_to product_path(product_id), notice: 'Product has been added to your cart.'
  end

  def remove
    product_id = params[:product_id].to_i
    $redis.hdel current_user_cart, product_id

    redirect_to :back, notice: 'Product has been removed from your cart.'
  end


  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticated

  def home
    @selection = Product.order("created_at DESC").limit(8)
  end

  # def authenticated
  #   redirect_to :products if signed_in?
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_herlper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def quantity_options(stock)
    array = (1..stock).map do |x|
      [x, x]
    end

    options_for_select(array)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/uploads/_form.html.erb
<%= form_for([:admin, @product, @upload], html: { multipart: true }) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% @upload.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl">
  <div class="upload">{%=o.name%}
    <div class="progress">
      <div class="progress-bar bar" style="width: 0%">
      </div>
    </div>
  </div>
</script>


  <div class="actions">
  <span class="btn btn-success fileinput-button">
  <i class="glyphicon glyphicon-plus"></i>
    <%= f.label :uploaded_file, t('.add_file') %>
    <%= f.file_field :uploaded_file, multiple: true, name: 'upload[image]' %>
       </span>
    <%= f.submit "Upload your images", class: "btn btn-primary pull-right" %>

  </div>
<% end %>

app/views/admin/uploads/_upload.html.erb
<%= image_tag(@upload.image(:medium), class: 'thumb')  %>

app/views/admin/uploads/create.js.erb
<% if @upload.new_record? %>
  alert('Failed');
<% else %>
  if ($('h1') !== undefined) {
    $('h1').append("<%=j render partial: 'admin/uploads/upload', locals: { upload: @upload } %>");
  }
<% end %>

app/views/admin/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/admin/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path, data: { no_turbolink: true } %>

app/views/admin/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_product_uploads_path %>

app/views/admin/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<%= render 'upload' %>
<br />

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', admin_product_uploads_path %>