config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  namespace :admin do
    resources :users
    resources :products do
      resources :uploads
    end
  end
  resources :stores

  resources :products do
    resources :comments
  end

  resources :favorite_products

  devise_for :users
  get 'pages/home'

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end

  def add_item(cart_item)
    @items << cart_item
  end

  def subtotal
    sum = 0
    @items.each do |item|
      sum += item.total
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :product_id, :quantity

  def initialize(product_id, quantity)
    @product_id = product_id
    @quantity = quantity
  end

  def product
    Product.find(product_id)
  end

  def total
    product.price * quantity.to_i
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
  belongs_to :state
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :uploads, :dependent => :destroy

  validates :name, :price, :quantity, presence: true
  validates :description, presence: true, length: { maximum: 300 }

  def in_cart?(current_user_id)
    $redis.hexists "cart#{current_user_id}", id
  end

  def cart_quantity
    $redis.hget "cart#{current_user_id}", id
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :user
  has_many :cities
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :city
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base

  belongs_to :product

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products
  has_many :comments
  belongs_to :city
  has_one :store
  has_many :favorites
  has_many :favorite_products, through: :favorites,
            source: :favorited, source_type: 'Product'

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def cart_count
    $redis.hlen "cart#{id}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"

  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @products = current_user.products.all
  end

  def show
    @upload = Upload.new
    @product = Product.find(params[:id])
    respond_with(@product)
  end

  def new
    @product = current_user.products.new
    respond_with(@product)
  end


  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to [:admin, @product], notice: 'Product was successfully created. Now just add some pictures and you are done.'
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to [:admin, @product], notice: 'Product was successfully updated. Do you need to change the pictures.'
    else
      render action: "edit"
    end
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def correct_user
      @product = current_user.products.find_by(id: params[:id])
      redirect_to products_path, notice: "Not authorized to edit this product" if @product.nil?
    end

    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
     info = $redis.hgetall current_user_cart
     @cart = Cart.new
     info.each do |product_id, quantity|
       @cart.add_item(CartItem.new(product_id, quantity))
     end

     @cart
  end

  def add
    product_id = params[:product_id].to_i
    quantity = params[:quantity].to_i
    $redis.hset current_user_cart, product_id, quantity

    redirect_to product_path(product_id), notice: 'Product has been added to your cart.'
  end

  def remove
    product_id = params[:product_id].to_i
    $redis.hdel current_user_cart, product_id

    redirect_to :back, notice: 'Product has been removed from your cart.'
  end


  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticated

  def home
    @selection = Product.order("created_at DESC").limit(8)
  end

  # def authenticated
  #   redirect_to :products if signed_in?
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @search = Product.search(params[:q])
    @products = @search.result(distinct: true)
  end

  def show
    @search = Product.search(params[:q])
    @product = Product.find(params[:id])
    respond_with(@product)
  end


  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stores = Store.all
    respond_with(@stores)
  end

  def show
    respond_with(@store)
  end

  def new
    @store = Store.new
    respond_with(@store)
  end

  def edit
  end

  def create
    @store = Store.new(store_params)
    @store.save
    respond_with(@store)
  end

  def update
    @store.update(store_params)
    respond_with(@store)
  end

  def destroy
    @store.destroy
    respond_with(@store)
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name, :city_id, :facebook, :twitter)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_herlper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def quantity_options(stock)
    array = (1..stock).map do |x|
      [x, x]
    end

    options_for_select(array)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<div class="form-style">

  <%= form_for [:admin, @product], html: { multipart: true } do |f| %>
    <% if @product.errors.any? %>
      <div class="alert alert-danger fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul>
           <% @product.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
           <% end %>
        </ul>
     </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :quantity %><br>
      <%= f.number_field :quantity, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price %><br>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group text-area">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit 'Create', class: 'btn btn-primary pull-right' %>
    </div>
  <% end %>

</div>

app/views/admin/products/edit.html.erb
<div class="row shadow-wrapper">
  <div id="crumbs">
    <ul class="nav nav-list">
      <li><%= link_to "Edit your product", edit_admin_product_path(@product) %></li>
      <li><%= link_to "Upload your pictures", edit_admin_product_upload_path(:admin, @product) %></li>

    </ul>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>

</div>

app/views/admin/products/index.html.erb
<div class="row shadow-wrapper">
  <div class="col-md-12">

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Pictures</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td>
        <span class="product-images"><% product.uploads.each do |upload| %>
          <%= image_tag(upload.image(:medium)) %>
        <% end %></span>
      </td>
      <td><%= product.quantity %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
      <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
      <td><%= link_to 'Destroy', admin_product_path(product),
                      method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

app/views/admin/products/new.html.erb
  <div class="row shadow-wrapper">
    <div id="crumbs">
      <ul class="nav nav-list">
        <li><%= link_to "Create a new product", new_admin_product_path %></li>
        <li class="disabled"><a href="#">Upload pictures</a></li>
      </ul>
    </div>
    <div class="col-md-6 col-md-offset-3">

      <%= render 'form' %>

    </div>
  </div>


<script>
$(document).ready(function() {
   $(".nav li.disabled a").click(function() {
     return false;
   });
});
</script>

app/views/admin/products/show.html.erb
<div class="row shadow-wrapper">
  <div id="crumbs">
    <ul class="nav nav-list">
      <li class="disabled"><a href="#">Create a new product</a></li>
      <li><a href="#">Upload pictures</a></li>
    </ul>
  </div>

  <div class="col-md-6 col-md-offset-3">
  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>
  <p>
    <strong>Stock:</strong>
    <%= @product.quantity %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>


  <%= render 'admin/uploads/form' %>

  </div>

  <div class="col-md-8 col-md-offset-2">
    <% @product.uploads.each do |upload| %>
    <div class="thumbnail uploaded-pictures">
      <%= image_tag(upload.image(:thumb)) %>
      <div class="caption">
        <%= link_to 'Delete', [:admin, @product, upload], method: :delete, class: "btn btn-alert", data: { confirm: "Are you sure?"} %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row">
    <%= link_to "Check your store", product_path(@product) , class: 'btn btn-warning pull-right'%>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <!-- Use HTML5 multiple attribute to enable multiple selection
           and pass back to controller all files as an array, ready
           for paperclip!!
           file_field_tag, since images is not a gallery attribute
       -->
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<div id="products" class="transitions-enabled">
  <% @products.each do |product| %>
    <div class="box panel panel-default">
      <% if product.uploads.any? %>
        <%= link_to image_tag(product.uploads.first.image.url(:medium)), product_path(product) %>
      <% end %>
      <div class="panel-body">
        <h5><%= product.name %></h5>
        <p class="pull-right">$<%= product.price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row shadow-wrapper">
  <div class="col-md-7">

  <div id="galleria">
    <% @product.uploads.each do |upload| %>
      <%= image_tag(upload.image(:medium)) %>
    <% end %>
  </div>


  <h4>Comments</h4>

  <% @product.comments.each do |comment| %>
   <%= render 'comments/comment', comment: comment %>
  <% end %>
  <%# we could replace these 3 lines with <%= render @product.comments %>

  <%= render 'comments/form' %>
  </div>

  <div class="col-md-5">
    <% if user_signed_in? %>
      <div class="add-favorite pull-right btn btn-default">
        <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <% unless current_user.favorite_products.exists?(id: @product.id) %>
        <%= link_to 'Add to favorites', favorite_products_path(product_id: @product), method: :post %>
        <% else %>
        <%= link_to 'Remove from favorites', favorite_product_path(@product), method: :delete %>
        <% end %>
      </div>
    <% end %>
  <div class="product-details">
    <h2>Product details</h2>
    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>
    <p>
      <strong>Stock:</strong>
      <%= @product.quantity %>
    </p>
    <p>
      <strong>Price:</strong>
      $<%= @product.price %>
    </p>
    </div>


    <div class="well well-sm well-cart clearfix">
  <%= form_tag add_to_cart_path(@product), method: :put do %>
    <div class="form-group col-sm-3 text-center">
      <%= label_tag :quantity %>
      <%= select_tag(:quantity, quantity_options(@product.quantity), {:class => 'form-control'}) %>
    </div>
    <div class="col-sm-9 text-center">
     <%if signed_in?%>
        <% if @product.in_cart?(current_user.id) %>
          <%= link_to "Remove from cart", remove_from_cart_path(@product), method: :put, class: "btn btn-warning btn-cart" %>
        <% else %>
          <button type="submit" class="btn btn-warning btn-cart">
            <span class='glyphicon glyphicon-shopping-cart'></span> Add to cart
          </button>
        <% end %>
     <%end%>
    </div>
  <% end %>

  </div>

  <%= render_shareable :buttons=> ['facebook', 'twitter', 'pinterest', 'google_plus'] %>


</div>

  <script>
    // Initialize Galleria
    Galleria.run('#galleria');
  </script>