config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  namespace :admin do
    resources :users
    resources :products do
      resources :uploads
    end
  end
  resources :stores

  resources :products do
    resources :comments
  end

  resources :favorite_products

  devise_for :users
  get 'pages/home'

  root 'products#index'

end

app/models/cart.rb
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end

  def add_item(cart_item)
    @items << cart_item
  end

  def subtotal
    sum = 0
    @items.each do |item|
      sum += item.total
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem
  attr_accessor :product_id, :quantity

  def initialize(product_id, quantity)
    @product_id = product_id
    @quantity = quantity
  end

  def product
    Product.find(product_id)
  end

  def total
    product.price * quantity.to_i
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
  belongs_to :state
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :uploads, :dependent => :destroy

  validates :name, :price, :quantity, presence: true
  validates :description, presence: true, length: { maximum: 300 }

  def in_cart?(current_user_id)
    $redis.hexists "cart#{current_user_id}", id
  end

  def cart_quantity
    $redis.hget "cart#{current_user_id}", id
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :user
  has_many :cities
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :city
  belongs_to :user
end

app/models/upload.rb
class Upload < ActiveRecord::Base

  belongs_to :product

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image, :attachment_presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :products
  has_many :comments
  belongs_to :city
  has_one :store
  has_many :favorites
  has_many :favorite_products, through: :favorites,
            source: :favorited, source_type: 'Product'

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def cart_count
    $redis.hlen "cart#{id}"
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
     info = $redis.hgetall current_user_cart
     @cart = Cart.new
     info.each do |product_id, quantity|
       @cart.add_item(CartItem.new(product_id, quantity))
     end

     @cart
  end

  def add
    product_id = params[:product_id].to_i
    quantity = params[:quantity].to_i
    $redis.hset current_user_cart, product_id, quantity

    redirect_to product_path(product_id), notice: 'Product has been added to your cart.'
  end

  def remove
    product_id = params[:product_id].to_i
    $redis.hdel current_user_cart, product_id

    redirect_to :back, notice: 'Product has been removed from your cart.'
  end


  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_herlper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-warning">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def quantity_options(stock)
    array = (1..stock).map do |x|
      [x, x]
    end

    options_for_select(array)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-sm-offset-2 nav-border">
        <h3  class="margin-top-0">Buy</h3>
        <ul class="list-unstyled">
          <li><%= link_to "All products", root_path %></li>
          <li><%= link_to "Your favorites", favorite_products_path %></li>
        </ul>
        </div>
        <div class="col-md-2 nav-border">
        <h3 class="margin-top-0">Sell</h3>
        <ul class="list-unstyled">
          <li><%= link_to "New product", new_admin_product_path %></li>
          <li><%= link_to "Edit you profile", edit_user_registration_path %></li>
        </ul>
      </div>
      <div class="col-md-4 ">
      <h3 class="margin-top-0">Our newsletter</h3>
        <p class=""> Sign in to receive all our update.</p>

      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar yamm navbar-default navbar-admin navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brand", root_path, class: "logo-center" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav green">
        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Buy & Sell <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <!-- Content container to add padding -->
              <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-2 col-sm-offset-2">
                    <h3  class="margin-top-0">Buy</h3>
                    <ul class="list-unstyled">
                      <li><%= link_to "All products", root_path %></li>
                      <li><%= link_to "Your favorites", favorite_products_path %></li>
                    </ul>
                    </div>
                    <div class="col-sm-2">
                    <h3 class="margin-top-0">Sell</h3>
                    <ul class="list-unstyled">
                      <li><%= link_to "New product", new_admin_product_path %></li>
                      <li><%= link_to "Edit you profile", edit_user_registration_path %></li>
                    </ul>
                  </div>
                  <div class="col-sm-2 nav-border">
                  <h3 class="margin-top-0">New Customer</h3>
                    <p class="">New to Brand? Create an account to get started today.</p>
                    <%= link_to "Register", new_user_registration_path, class: "btn btn-warning btn-register" %>
                  </div>
                  <div class="col-sm-2">
                  <h3 class="margin-top-0">Sign in</h3>
                    <ul class="list-unstyled">
                      <li><%= form_for(:user, :url => session_path(:user)) do |f| %>
                          <div class="form-group">
                          <%= f.text_field :email, placeholder: "Email", class: "input-small form-control" %>
                          </div>
                          <div class="form-group">
                          <%= f.password_field :password, :placeholder => "Password", class: "input-small form-control"  %>
                          </div>
                          <div class="form-group">
                          <%= f.check_box :remember_me, class: "checkbox" %><%= f.label :remember_me, class: "checkbox" %>
                          </div>
                          <%= f.submit 'Login', class: "btn btn-warning" %>
                        <% end %></li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right green">
        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
          <ul class="dropdown-menu" role="menu">
          <%= search_form_for @search, html: { class: "form-inline search-form"} do |f| %>
            <%= f.text_field :name_or_description_cont, class: "search-input form-control", autofocus: true, placeholder: "Search..." %>
          <% end %>
          </ul>
        </li>
        <li><%= link_to favorite_products_path do %>
          <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          <% if user_signed_in? %>
              <span class="badge"><%=current_user.favorite_products.count%></span>
            <% end %>
          <% end %>
        <li>
          <%= link_to cart_path do %>
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <% if user_signed_in? %>
              <span class="badge"><%=current_user.cart_count%></span>
            <% end %>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown" role="button" aria-expanded="false">
          <% if user_signed_in? %>
          <%= image_tag Gravatar.new(current_user.email).image_url, :class => "image-circle" %>
          <% else %>
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          <% end %>
          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
            <li><%= link_to "Dashboard", admin_products_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>SCREcommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="wrapper" class="">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <div class="sidebar-nav">
      <h3>Dashboard</h3>
    <ul class="border-bottom">
      <h4>User admin</h4>
      <li><%= link_to "All user", admin_users_path %></li>
    </ul>
    <ul class="border-bottom">
      <h4>My profile</h4>
      <li><%= link_to "Edit profile", edit_user_registration_path %></li>
      <li>
      </li>
    </ul>
    <ul class="border-bottom">
      <h4>Favorites</h4>
      <li><%= link_to "Your favorites", favorite_products_path %></li>
    </ul>
    <ul>
      <h4>Products</h4>
      <li><%= link_to "All products", admin_products_path %></li>
      <li><%= link_to "New product", new_admin_product_path %></li>

    </ul>

    </div>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
    <%= link_to new_admin_product_path, class: "btn btn-warning pull-right" do %>
      <span class="glyphicon glyphicon-plus"></span> New product
    <% end %>
      <div class="container-fluid">

        <%# Rails flash messages styled for Bootstrap 3.0 %>
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>

        <%= yield %>
  </div>
  <!-- /#page-content-wrapper -->
  </div>



</div>

  <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
  </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCREcommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <link href="https://fontastic.s3.amazonaws.com/kancBMMmZqpEycnUGQpBcn/icons.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<%= yield %>
</div>

<%= render 'layouts/footer' %>


</body>
</html>

app/views/pages/cart.html.erb
<div class="row">
  <div class="col-sm-12 col-md-10 col-md-offset-1">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th class="text-center">Price</th>
          <th class="text-center">Total</th>
          <th> </th>
        </tr>
      </thead>
      <tbody>
      <% @cart_products.each do |product|%>
        <tr>
          <td class="col-sm-8 col-md-6">
          <div class="media">
            <a class="thumbnail pull-left" href="#"> <img class="media-object" src="http://icons.iconarchive.com/icons/custom-icon-design/flatastic-2/72/product-icon.png" style="width: 72px; height: 72px;"> </a>
            <div class="media-body">
              <h4 class="media-heading"><a href="#"><%= product.name %></a></h4>
            </div>
          </div></td>
            <td class="col-sm-1 col-md-1" style="text-align: center">
            <input type="email" class="form-control" id="exampleInputEmail1" value="3">
            </td>
            <td class="col-sm-1 col-md-1 text-center"><strong>$<%= product.price %></strong></td>
            <td class="col-sm-1 col-md-1 text-center"><strong>$14.61</strong></td>
            <td class="col-sm-1 col-md-1">

              <span class="glyphicon glyphicon-remove"></span>
              <%=link_to "Reddddddmove" , remove_from_cart_path(product), method: :put %>
            </button></td>
        </tr>

        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Subtotal</h5></td>
            <td class="text-right"><h5><strong>$24.59</strong></h5></td>
        </tr>
        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h5>Estimated shipping</h5></td>
            <td class="text-right"><h5><strong>$6.94</strong></h5></td>
        </tr>
        <tr>
            <td>   </td>
            <td>   </td>
            <td>   </td>
            <td><h3>Total</h3></td>
            <td class="text-right"><h3><strong>$31.53</strong></h3></td>
        </tr>
        <tr>
          <td>   </td>
          <td>   </td>
          <td>   </td>
          <td>
          <button type="button" class="btn btn-default">
              <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
          </button></td>
          <td>
          <button type="button" class="btn btn-success">
              Checkout <span class="glyphicon glyphicon-play"></span>
          </button></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/pages/home.html.erb
</div>
<div class="row carousel">

</div>

<section class="marketing">
<div class="container">
  <div class="row"></div>
  <div class="col-sm-4 col-md-4 text-center">
    <i class="icon-picture"></i>
    <h4>Enjoy a selection of unique product, handmades, in limited series that  you won't find anywhere else</h4>
  </div>
  <div class="col-sm-4 col-md-4 text-center">
    <i class="icon-earth-globe-streamline"></i>
    <h4>Our products come from all over the world. </h4>
  </div>
  <div class="col-sm-4 col-md-4 text-center">
    <i class="icon-computer-imac"></i>
    <h4>And all from the confort of your own home. We have also worked hard so that you can browse aour website in your tablet and phone.</h4>
  </div>
  </div>
</section>

<div class="container">
  <span class="glyphicon glyphicon-gift icon-center"></span>
  <h3 class="text-center">Check out some of the latest products</h3>
</div>



<div class="container">
<div class="row">

<div id="products" class="transitions-enabled">
  <% @selection.each do |product| %>
    <div class="box panel panel-default">
      <% if product.uploads.any? %>
        <%= link_to image_tag(product.uploads.first.image.url(:medium)), product_path(product) %>
      <% end %>
      <div class="panel-body">
        <h5><%= product.name %></h5>
      </div>
    </div>
  <% end %>
</div>


</div>
</div>
</div>